apiVersion: v1
kind: Plugin
metadata:
  author: Typer_Body
  name: MarkDown2img
  repository: 'https://github.com/TwperBody/Langbot_M2Img'
  version: 2.1.0
  description:
    en_US: 将ai内容中的markdown消息进行转换成图片
    zh_Hans: 将ai内容中的markdown消息进行转换成图片
  label:
    en_US: Markdowm2ing
    zh_Hans: Markdowm2ing
  icon: assets/icon.svg
spec:
  config:
    - name: get_url
      type: boolean
      label: 
        zh_Hans: 提取Markdown中的链接
      description:
        zh_Hans: 是否打开专门提取Markdown中的链接
      required: True
      default: False
    - name: get_markdown
      type: integer
      label:
        zh_Hans: markdown转义触发量
      description:
        zh_Hans: 转换触发权重
      required: True
      default: 3
    - name: side_of_markdown
      type: integer
      label:
        zh_Hans: markdown图片宽度
      description:
        zh_Hans: markdown图片宽度
      required: True
      default: 800
    - name: breakout
      type: boolean
      label:
        zh_Hans: 阻止未处理的markdown消息回复
      description:
        zh_Hans: 阻止未处理的markdown消息回复
      required: True
      default: True
    - name: out_photo
      type: boolean
      label:
        zh_Hans: 输出图片地址
      description:
        zh_Hans: 是否输出图片地址
      required: False
      default: False
    - name: test
      type: boolean
      label:
        zh_Hans: 调试输出
      description:
        zh_Hans: 调试输出
      required: False
      default: False
  components:
    EventListener:
      fromDirs:
        - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: Markdowm2ing

